---
k3s_version: v1.29.0+k3s1 #v1.17.5+k3s1 #v1.21.6+k3s1  # 1.22.3?
ansible_user: vagrant #debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--flannel-iface=eth1" # for vagrant setup else ""
extra_agent_args: "--flannel-iface=eth1" # for vagrant setup else

ansible_port: 22
ansible_ssh_user: vagrant
ansible_python_interpreter: "/usr/bin/python3"